services:
  postgres:
    image:  postgres:15.7-alpine3.20
    container_name: postgres-dev
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    restart: unless-stopped
    networks:
      - network_app

networks:
  network_app:
    driver: bridge